name: software-engineering-lab-9
on:
  push:
    branches:
      - main
jobs:
  docs:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4 # change to your Python version
      - name: Install dependencies
        run: |
          python -m venv list_4
          source list_4/bin/activate
          pip install -r requirements.txt
          pip install djangorestframework_simplejwt
          pip install drf_yasg

    # make sure your requirements file is up to date
      - name: Generate API documentation
        run: |
          source list_4/bin/activate
          python manage.py generateschema > docs.json
    # modiify the paths if necessary
      - name: Commit and push documentation
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json index.html 
          git commit -m "Updated documentation"
          git push origin main
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  test:
    runs-on: ubuntu-latest
    services:
            db:
              image: postgres:17
              env:
                POSTGRES_USER: testuser
                POSTGRES_PASSWORD: testpassword
                POSTGRES_DB: testdb
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and start Containers
        run: docker-compose up --build -d
      - name: Execute unit tests
        run: docker exec $(docker-compose ps -q api) python
          manage.py test myapp/tests
    # modiify the path if necessaryyy