name: software-engineering-lab-9
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4 # change to your Python version
      - name: Install dependencies
        run: |
          python -m venv list_4
          source list_4/bin/activate
          pip install -r requirements.txt
          pip install djangorestframework_simplejwt
    # make sure your requirements file is up to date
      - name: Generate API documentation
        run: |
          source list_4/bin/activate
          python manage.py generateschema > docs.json
    # modiify the paths if necessary
      - name: Commit and push documentation
        run: |
          git config --global user.mail
          "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json index.html # modify the paths if necessary
          git commit -m "Updated documentation"
          git push origin main
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}